;; load modules
(load-library "~/emacs/theme")
(load-library "~/emacs/org")
(load-library "~/emacs/rainbow-delimiters")
(load-library "~/emacs/redoplus")
(load-library "~/emacs/daemon")
(load-library "~/emacs/common")
(load-library "~/emacs/locale")
(load-library "~/emacs/printer")
(load-library "~/emacs/gpg")
